// Generated by CoffeeScript 1.6.2
(function() {
  var msecPerWord, splitWord;

  window.wpm = 200;

  msecPerWord = function(wpm) {
    return 1 / (wpm / 60 / 1000);
  };

  splitWord = function(w) {
    var midpoint, wordLength;

    wordLength = w.length;
    midpoint = Math.floor(w.length / 2);
    return [w.slice(0, midpoint), w[midpoint], w.slice(1 + midpoint)];
  };

  $(function() {
    var $left, $mid, $right, essay, essay_arr, essay_len, index, refreshWord, setWord,
      _this = this;

    $("#wpm").change(function() {
      return window.wpm = $($('#wpm').children(':selected')).val();
    });
    window.essay = "[loading]";
    $.ajax("essays/tranquil.html", {
      async: false,
      success: function(resp) {
        return window.essay = resp;
      }
    });
    essay = window.essay;
    essay_arr = essay.split(' ');
    essay_len = essay_arr.length;
    index = 0;
    refreshWord = function() {
      if (index > essay_len) {
        console.info("Done!");
        return clearInterval(interval);
      } else {
        setWord(essay_arr[index]);
        return index = index + 1;
      }
    };
    $left = $('#word > #left');
    $mid = $('#word > #mid');
    $right = $('#word > #right');
    setWord = function(word) {
      var left, mid, right, _ref;

      if (/[?,.!;]$/.test(word)) {
        setTimeout(function() {
          return refreshWord();
        }, msecPerWord(window.wpm / 4));
      } else {
        setTimeout(refreshWord, msecPerWord(window.wpm));
      }
      _ref = splitWord(word), left = _ref[0], mid = _ref[1], right = _ref[2];
      $left.text(left);
      $mid.text(mid);
      return $right.text(right);
    };
    return refreshWord();
  });

}).call(this);
