// Generated by CoffeeScript 1.6.2
(function() {
  var N;

  window.seneca = {
    essay_id: 'essays/tranquil.html',
    essay: '',
    essay_arr: [],
    essay_len: 0,
    index: 0,
    wpm: 200,
    interval: null,
    msecPerWord: function(wpm) {
      return 1 / (wpm / 60 / 1000);
    },
    stripHTML: function(w) {
      return w.replace(/<(?:.|\n)*?>/gm, '');
    },
    splitWord: function(w) {
      var midpoint, wordLength;

      wordLength = w.length;
      midpoint = Math.floor(w.length / 2);
      return [w.slice(0, midpoint), w[midpoint], w.slice(1 + midpoint)];
    }
  };

  N = window.seneca;

  $(function() {
    var $left, $mid, $right, getWordWidth, refreshWord, setWord;

    $("#wpm").change(function() {
      return N.wpm = $($('#wpm').children(':selected')).val();
    });
    $("#texts").change(function() {
      var _this = this;

      clearInterval(N.interval);
      N.index = 0;
      N.essay_id = $("#texts").children(":selected").val();
      return $.ajax(N.essay_id, {
        async: false,
        success: function(resp) {
          var delta;

          N.essay_arr = resp.split(' ');
          N.essay_len = N.essay_arr.length;
          return setWord("Have Fun :)", delta = 1000);
        }
      });
    });
    $('#texts').children().first().attr(':selected', 'true');
    refreshWord = function() {
      if (N.index > N.essay_len) {
        return clearInterval(N.interval);
      } else {
        setWord(N.stripHTML(N.essay_arr[N.index]));
        return N.index++;
      }
    };
    $left = $('#word > #left');
    $mid = $('#word > #mid');
    $right = $('#word > #right');
    getWordWidth = function(word) {
      var w, width;

      w = $("<div class='word' style='display: inline-block'>" + word + "</div>").appendTo('#essay');
      width = w.width();
      $('#essay').children().remove();
      return width;
    };
    return setWord = function(word, delta) {
      var left, mid, right, _ref;

      if (delta == null) {
        delta = 0;
      }
      if (/[?,.!;]$/.test(word)) {
        N.interval = setTimeout(function() {
          return refreshWord();
        }, N.msecPerWord(N.wpm / 4) + delta);
      } else {
        N.interval = setTimeout(refreshWord, N.msecPerWord(N.wpm) + delta);
      }
      _ref = N.splitWord(word), left = _ref[0], mid = _ref[1], right = _ref[2];
      $left.css('margin-left', -1 * getWordWidth(left));
      $left.html(left);
      $right.css('margin-left', getWordWidth(mid));
      $mid.html(mid);
      return $right.html(right);
    };
  });

}).call(this);
